# Generated by Django 5.1.2 on 2024-10-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
