# Generated by Django 5.1.2 on 2024-11-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
